// import "../../public/assets/css/all.css";

import Head from "next/head";
import { useEffect } from "react";
import SmoothPageScroll from "../components/common/SmoothPageScroll";
import "../styles/main.css";

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    import("../../public/assets/js/bootstrap.bundle.min.js");
  });
  return (
    <>
      <Head>
        <title>
          TechGen - Digital Agency and Technology React NextJs Template
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="assets/images/icons/logo-icon.svg" />
      </Head>
      <Component {...pageProps} />
      <SmoothPageScroll />
    </>
  );
}

export default MyApp;
