import React, { useState } from "react";
// import About5 from "../components/about/About5";
// import Banner5 from "../components/banner/Banner5";
// import Index5Blog from "../components/blog/Index5Blog";
// import CaseStudy5 from "../components/caseStudy/CaseStudy5";
// import Customar from "../components/clientSection/Customar";
// import Preloader from "../components/common/Preloader";
// import Sidebar from "../components/common/Sidebar";
// import Contact5 from "../components/contact/Contact5";
// import Footer from "../components/footer/Footer";
// import Header1 from "../components/header/Header1";
// import Service5 from "../components/service/Service5";
// import Team5 from "../components/team/Team5";
// import Testimonial5 from "../components/testimonial/Testimonial5";
// import Topbar1 from "../components/topbar/Topbar1";
// import Video5 from "../components/video/Video5";
// import WorkProcess5 from "../components/workprocess/WorkProcess5";
import Head from "next/head";
import Header3 from "../components/header/Header3";
import Preloader from "../components/common/Preloader";
import About3 from "../components/about/About3";
import Banner3 from "../components/banner/Banner3";
import Blog3 from "../components/blog/Blog3";
import CaseStudy3 from "../components/caseStudy/CaseStudy3";
import Contacte3 from "../components/contact/Contacte3";
import Customar3 from "../components/customar/Customar3";
import Footer3 from "../components/footer/Footer3";
import Service3 from "../components/service/Service3";
import Team3 from "../components/team/Team3";
import Testimonial3 from "../components/testimonial/Testimonial3";
import Video3 from "../components/video/Video3";

function Home() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  return (
    // <>
    //  <Head>
    //     <title>
    //     MrGroup - MR Consulting Group
    //     </title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="assets/images/MrConsultingGroup/icono/icono MrGroup.svg" />
    //   </Head>
    //   <Preloader />
    //   <Topbar1 />
    //   <Header1 />
    //   <Sidebar sidebarOpen={sidebarOpen} setSidebarOpen={setSidebarOpen} />
    //   <Banner5 setSidebarOpen={setSidebarOpen} />
    //   <About5 />
    //   <Service5 />
    //   <CaseStudy5 />
    //   <Video5 />
    //   <WorkProcess5 />
    //   <Testimonial5 />
    //   <Customar />
    //   <Team5 />
    //   <Contact5 />
    //   <Index5Blog />
    //   <Footer />
    // </>


    <>
    <Head>
       <title>MrGroup - MR Consulting Group</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="assets/images/MrConsultingGroup/icono/mrcgr_svg01.svg" />
    </Head>
    <Header3 />
    {/* <Preloader /> */}
    <Banner3 />
    <About3 />
    <Video3 />
    <Service3 />
    {/* <Customar3 />
    <Testimonial3 /> */}
    <Contacte3 />
    {/* <CaseStudy3 /> */}
    {/* <Team3 /> */}
    {/* <Blog3 /> */}
    <div className="servcie-section pt-120 overflow-hidden"></div>
    <Footer3 />
    </>
  );
}

export default Home;
